apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node
  template:
    metadata:
      labels:
        app: my-node
    spec:
      containers:
      - name: my-node-container
        image: my-node-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
